from typing import List

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from app_electron.ai_model.api.model_service import predict, get_model_info

app = FastAPI(title="ElectroChem AI API", description="API for electrochemical substance prediction using XGBoost.", version="1.0.0",)

# REQUEST MODEL
class PredictionRequest(BaseModel):features: List[float] = Field(
        ...,
        description="15-feature vector generated by Flutter app."
        )

# RESPONSE MODEL

class PredictionResponse(BaseModel):
    substance: str
    class_index: int
    confidence: float

# ROOT

@app.get("/")
def root():
    return {
        "status": "ok",
        "service": "ElectroChem AI API",
        "model": "XGBoost",
        "features": 15,
    }

# MODEL INFO

@app.get("/model-info")
def model_info(): return get_model_info()

# PREDICTION

@app.post(
    "/predict",
    response_model=PredictionResponse
)
def prediction(request: PredictionRequest):

    try:

        result = predict(
            request.features
        )

        return result

    except ValueError as e:

        raise HTTPException(
            status_code=400,
            detail=str(e)
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=f"Prediction error: {str(e)}"
        )